apps/booking/urls.py
from django.urls import path
from .views import room, room_detail

app_name = 'booking'

urlpatterns = [
    path('room/', room, name='room'),
    path('room/detail/<slug:slug>/', room_detail, name='room_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('apps.home.urls', namespace='home')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('contact/', include('apps.contact.urls', namespace='contact')),
    path('booking/', include('apps.booking.urls', namespace='booking')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/booking/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from ckeditor.fields import RichTextField


class BookingBaseModel(models.Model):
    name = models.CharField(max_length=221)
    modified_date = models.DateTimeField(auto_now=True)
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomService(BookingBaseModel):
    image = models.ImageField(upload_to='rooms/services/', null=True, blank=True)


class Room(BookingBaseModel):
    slug = models.SlugField(null=True, blank=True, unique=True)
    size = models.CharField(max_length=221)
    capacity = models.IntegerField()
    price = models.DecimalField(max_digits=5, decimal_places=2)  # $999.99
    services = models.ManyToManyField(RoomService)
    description = RichTextField(null=True, blank=True)

    def is_free(self, check_in, check_out):
        bookings = self.bookings.filter(
            check_out__gt=check_in,
            check_in__lt=check_out
        )
        return not bookings.exists()


class RoomImage(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='rooms/')


class RoomReview(BookingBaseModel):
    MARK = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    )
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='reviews')
    image = models.ImageField(upload_to='rooms/reviews', null=True, blank=True)
    mark = models.IntegerField(choices=MARK)
    message = models.TextField()


class Booking(models.Model):
    client_name = models.CharField(max_length=221)
    client_phone = models.CharField(max_length=16)
    room = models.ForeignKey(Room, on_delete=models.SET_NULL, null=True, blank=True, related_name='bookings')
    check_in = models.DateField()  # 2023-07-01
    check_out = models.DateField()  # 2023-07-04
    capacity = models.IntegerField()
    created_date = models.DateTimeField(auto_now_add=True)

    @property
    def days(self):
        days_delta = self.check_out - self.check_in
        return days_delta.days

    @property
    def total(self):
        total = self.days * self.room.price
        return total


def room_pre_save(instance, sender, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.name + instance.size)


pre_save.connect(room_pre_save, sender=Room)

apps/booking/views.py
import datetime

from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, HttpResponse, redirect

from .models import Room, RoomReview, Booking


def room(request):
    rooms = Room.objects.order_by('-id')
    checkin = request.GET.get('checkin-date')  # '2023-07-05'
    checkout = request.GET.get('checkout-date')
    adults = request.GET.get('adults')
    children = request.GET.get('children')
    data = [checkin, checkout, adults, children]

    credentials = [checkin, checkout, adults, children]
    if all(credentials):
        count_person = int(adults) + int(children)
        if checkin > checkout:
            return HttpResponse("checkout must be grater than checkin")
        checkin_lst = checkin.split('-')  # ['2023', '07', '05']
        checkin_date = datetime.date(int(checkin_lst[0]), int(checkin_lst[1]), int(checkin_lst[2]))  # 2023-07-05
        if checkin_date < datetime.datetime.today().date():
            return HttpResponse("checkin must be grater than today")

        busy_rooms_set = set()

        bookings = Booking.objects.filter(
            check_out__gte=checkin,
            check_in__lte=checkout
        ).values_list('room_id',)
        print(bookings)
        for i in bookings:
            busy_rooms_set.add(i[0])
        print(busy_rooms_set)
        rooms = Room.objects.exclude(id__in=busy_rooms_set)
        # rooms = Room.objects.filter(Q(Q(bookings__check_in__gt=checkout) |
        #                               Q(bookings__check_out__lte=checkin) |
        #                               Q(bookings__isnull=True)) & Q(capacity__gte=count_person)).distinct()
        # rooms = Room.objects.exclude(Q(bookings__check_in__lte=checkout), Q(bookings__check_out__gte=checkin))
        # User.objects.exclude(id=request.user.id)

    paginator = Paginator(rooms, 5)  # Show 5 rooms per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    data_url = f"checkin-date={checkin}&checkout-date={checkout}&adults={adults}&children={children}"
    ctx = {
        "object_list": page_obj,
        "data_url": data_url,
    }
    return render(request, 'booking/room.html', ctx)


def room_detail(request, slug):
    room = get_object_or_404(Room, slug=slug)
    reviews = RoomReview.objects.filter(room_id=room.id)
    checkout = request.GET.get('checkout-date')
    checkin = request.GET.get('checkin-date')
    adults = request.GET.get('adults')
    children = request.GET.get('children')

    if request.method == "POST":
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        print(checkout, checkin, adults, children)
        if adults == 'None' or children == 'None' or not checkin or not checkout:
            messages.info(request, 'firstly you should search your room')
            return redirect('booking:room')

        if name and phone:
            capacity = int(adults) + int(children)
            obj = Booking.objects.create(client_name=name, client_phone=phone, room_id=room.id, check_in=checkin,
                                         check_out=checkout, capacity=capacity)
            messages.success(request, 'You have successfully booked this room')
            return redirect('.')
        messages.info(request, 'Your name and phone number must not be empty')

    ctx = {
        'object': room,
        'reviews': reviews,
    }
    return render(request, 'booking/single-room.html', ctx)

templates/booking/room.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="breadcrumb-area bg-img bg-overlay jarallax"
         style="background-image: url({% static 'img/bg-img/16.jpg' %});">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12">
                    <div class="breadcrumb-content text-center">
                        <h2 class="page-title">Our Room</h2>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb justify-content-center">
                                <li class="breadcrumb-item"><a href="../home/index-2.html">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Room</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="roberto-rooms-area section-padding-100-0">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-8">
                    {% for object in object_list %}

                        <div class="single-room-area d-flex align-items-center mb-50 wow fadeInUp"
                             data-wow-delay="100ms">

                            <div class="room-thumbnail">
                                <img src="{{ object.roomimage_set.first.image.url }}" alt="">
                            </div>

                            <div class="room-content">
                                <h2>{{ object.name }}</h2>
                                <h4>{{ object.price }}$ <span>/ Day</span></h4>
                                <div class="room-feature">
                                    <h6>Size: <span>{{ object.size }}</span></h6>
                                    <h6>Capacity: <span>Max persion {{ object.capacity }}</span></h6>
                                    <h6>Bed: <span>King beds</span></h6>
                                    <h6>Services:
                                        <span>
                                        {% for service in object.services.all %}
                                            {{ service.name }},
                                        {% endfor %}
                                    </span>
                                    </h6>
                                </div>
                                <a href="{% url 'booking:room_detail' object.slug %}?{{ data_url }}"
                                   class="btn view-detail-btn">View
                                    Details <i class="fa fa-long-arrow-right"
                                               aria-hidden="true"></i></a>
                            </div>
                        </div>

                    {% endfor %}


                    <nav class="roberto-pagination wow fadeInUp mb-100" data-wow-delay="600ms">
                        <ul class="pagination">
                            {% if object_list.has_previous %}
                                <li class="page-item"><a class="page-link"
                                                         href="?page={{ object_list.previous_page_number }}"> < Previous
                                    <i class="fa fa-angle-left"></i></a>
                                </li>
                            {% endif %}

                            {% for page in object_list.paginator.page_range %}
                                {% if page == object_list.number %}
                                    <li class="page-item active"><a class="page-link"
                                                                    href="?page={{ page }}">{{ page }}</a>
                                    </li>
                                {% else %}
                                    <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}

                            {% if object_list.has_next %}
                                <li class="page-item"><a class="page-link"
                                                         href="?page={{ object_list.next_page_number }}">Next
                                    <i class="fa fa-angle-right"></i></a>
                                </li>
                            {% endif %}

                        </ul>
                    </nav>
                </div>
                <div class="col-12 col-lg-4">

                    <div class="hotel-reservation--area mb-100">
                        <form action="#" method="get">
                            <div class="form-group mb-30">
                                <label for="checkInDate">Date</label>
                                <div class="input-daterange" id="datepicker">
                                    <div class="row no-gutters">
                                        <div class="col-6">
                                            <input type="date" class="input-small form-control" id="checkInDate"
                                                   name="checkin-date" placeholder="Check In">
                                        </div>
                                        <div class="col-6">
                                            <input type="date" class="input-small form-control" name="checkout-date"
                                                   placeholder="Check Out">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group mb-30">
                                <label for="guests">Guests</label>
                                <div class="row">
                                    <div class="col-6">
                                        <select name="adults" id="guests" class="form-control">
                                            <option value="1">1</option>
                                            <option value="2">2</option>
                                            <option value="3">3</option>

                                        </select>
                                    </div>
                                    <div class="col-6">
                                        <select name="children" id="children" class="form-control">
                                            <option value="1">1</option>
                                            <option value="2">2</option>
                                            <option value="3">3</option>

                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group mb-50">
                                <div class="slider-range">
                                    <div class="range-price">Max Price: $0 - $3000</div>
                                    <div data-min="0" data-max="3000" data-unit="$"
                                         class="slider-range-price ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all"
                                         data-value-min="0" data-value-max="3000" data-label-result="Max Price: ">
                                        <div class="ui-slider-range ui-widget-header ui-corner-all"></div>
                                        <span class="ui-slider-handle ui-state-default ui-corner-all"
                                              tabindex="0"></span>
                                        <span class="ui-slider-handle ui-state-default ui-corner-all"
                                              tabindex="0"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn roberto-btn w-100">Search</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/booking/single-room.html
{% extends 'base.html' %}
{% load static %}
{% load range_filter %}
{% block content %}

    <div class="breadcrumb-area bg-img bg-overlay jarallax"
         style="background-image: url({% static 'img/bg-img/16.jpg' %});">
        <div class="container h-100">
            <div class="row h-100 align-items-end">
                <div class="col-12">
                    <div class="breadcrumb-content d-flex align-items-center justify-content-between pb-5">
                        <h2 class="room-title">{{ object.name }}</h2>
                        <h2 class="room-price">${{ object.price }} <span>/ Per Night</span></h2>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="roberto-rooms-area section-padding-100-0">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-8">

                    <div class="single-room-details-area mb-50">

                        <div class="room-thumbnail-slides mb-50">
                            <div id="room-thumbnail--slide" class="carousel slide" data-ride="carousel">
                                <div class="carousel-inner">

                                    <div class="carousel-item active">
                                        <img src="{{ object.roomimage_set.first.image.url }}" class="d-block w-100"
                                             alt="">
                                    </div>

                                </div>
                                <ol class="carousel-indicators">
                                    {% for img in object.roomimage_set.all %}

                                        <li data-target="#room-thumbnail--slide" data-slide-to="{{ forloop.counter0 }}"
                                            class="{% if forloop.counter0 == 0 %}active{% endif %}">
                                            <img src="{{ img.image.url }}" class="d-block w-100" alt="">
                                        </li>

                                    {% endfor %}

                                </ol>
                            </div>
                        </div>

                        <div class="room-features-area d-flex flex-wrap mb-50">
                            <h6>Size: <span>{{ object.size }}</span></h6>
                            <h6>Capacity: <span>Max persion {{ object.capacity }}</span></h6>
                            <h6>Bed: <span>King beds</span></h6>
                            <h6>Services: <span>{% for i in object.services.all %}{{ i.name }}, {% endfor %}</span></h6>
                        </div>

                        {{ object.description|safe }}

                    </div>

                    <div class="room-service mb-50">
                        <h4>Room Services</h4>
                        <ul>
                            {% for foo in object.services.all %}
                                <li><img src="{{ foo.image.url }}" alt=""> {{ foo.name }}</li>
                            {% endfor %}


                        </ul>
                    </div>

                    <div class="room-review-area mb-100">
                        <h4>Room Review</h4>
                        {% for review in reviews %}
                            <div class="single-room-review-area d-flex align-items-center">
                                <div class="reviwer-thumbnail">
                                    {% if review.image %}
                                        <img src="{{ review.image.url }}" alt="">
                                    {% else %}
                                        <img src="{% static 'img/bg-img/53.jpg' %}" alt="">
                                    {% endif %}
                                </div>
                                <div class="reviwer-content">
                                    <div class="reviwer-title-rating d-flex align-items-center justify-content-between">
                                        <div class="reviwer-title">
                                            <span>{{ review.created_date }}</span>
                                            <h6>{{ review.name }}</h6>
                                        </div>

                                        <div class="reviwer-rating">
                                            {% for i in review.mark|range_filter:"1,1" %}
                                                <i class="fa fa-star"></i>
                                            {% endfor %}

                                        </div>
                                    </div>
                                    <p>{{ review.message }}</p>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                </div>
                <div class="col-12 col-lg-4">

                    <div class="hotel-reservation--area mb-100">
                        <form action="#" method="post">
                            {% csrf_token %}
                            <div class="form-group mb-30">
                                <label for="name">Name</label>

                                <div class="row no-gutters">
                                    <div class="col-12">
                                        <input type="text" class="input-small form-control" name="name"
                                               id="name" placeholder="Your name" required>
                                    </div>
                                </div>

                            </div>
                            <div class="form-group mb-30">
                                <label for="phone">Phone</label>
                                <div class="row no-gutters">
                                    <div class="col-12">
                                        <input type="text" class="input-small form-control" name="phone"
                                               id="phone" placeholder="90.000-00-00" required>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn roberto-btn w-100">Booking</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}