apps/blog/urls.py
from django.urls import path
from .views import blog, blog_detail

app_name = 'blog'

urlpatterns = [
    path('', blog, name='blog'),
    path('detail/<int:year>/<int:month>/<int:day>/<slug:slug>/', blog_detail, name='blog_detail'),
]

apps/booking/urls.py
from django.urls import path
from .views import room, room_detail

app_name = 'booking'

urlpatterns = [
    path('room/', room, name='room'),
    path('room/detail/<slug:slug>/', room_detail, name='room_detail'),
]

apps/contact/urls.py
from django.urls import path
from .views import contact

app_name = 'contact'

urlpatterns = [
    path('', contact, name='contact'),
]

apps/home/urls.py
from django.urls import path
from .views import home, about

app_name = 'home'


urlpatterns = [
    path('', home, name='index'),
    path('about/', about, name='about'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('apps.home.urls', namespace='home')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('contact/', include('apps.contact.urls', namespace='contact')),
    path('booking/', include('apps.booking.urls', namespace='booking')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Roberto - Hotel &amp; Resort HTML Template</title>

    <link rel="icon" href="{% static 'img/core-img/favicon.png' %}">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script nonce="38db34de-c43d-44c6-9f85-c5f886fd4a94">(function (w, d) {
        !function (dK, dL, dM, dN) {
            dK[dM] = dK[dM] || {};
            dK[dM].executed = [];
            dK.zaraz = {deferred: [], listeners: []};
            dK.zaraz.q = [];
            dK.zaraz._f = function (dO) {
                return function () {
                    var dP = Array.prototype.slice.call(arguments);
                    dK.zaraz.q.push({m: dO, a: dP})
                }
            };
            for (const dQ of ["track", "set", "debug"]) dK.zaraz[dQ] = dK.zaraz._f(dQ);
            dK.zaraz.init = () => {
                var dR = dL.getElementsByTagName(dN)[0], dS = dL.createElement(dN),
                    dT = dL.getElementsByTagName("title")[0];
                dT && (dK[dM].t = dL.getElementsByTagName("title")[0].text);
                dK[dM].x = Math.random();
                dK[dM].w = dK.screen.width;
                dK[dM].h = dK.screen.height;
                dK[dM].j = dK.innerHeight;
                dK[dM].e = dK.innerWidth;
                dK[dM].l = dK.location.href;
                dK[dM].r = dL.referrer;
                dK[dM].k = dK.screen.colorDepth;
                dK[dM].n = dL.characterSet;
                dK[dM].o = (new Date).getTimezoneOffset();
                if (dK.dataLayer) for (const dX of Object.entries(Object.entries(dataLayer).reduce(((dY, dZ) => ({...dY[1], ...dZ[1]})), {}))) zaraz.set(dX[0], dX[1], {scope: "page"});
                dK[dM].q = [];
                for (; dK.zaraz.q.length;) {
                    const d_ = dK.zaraz.q.shift();
                    dK[dM].q.push(d_)
                }
                dS.defer = !0;
                for (const ea of [localStorage, sessionStorage]) Object.keys(ea || {}).filter((ec => ec.startsWith("_zaraz_"))).forEach((eb => {
                    try {
                        dK[dM]["z_" + eb.slice(7)] = JSON.parse(ea.getItem(eb))
                    } catch {
                        dK[dM]["z_" + eb.slice(7)] = ea.getItem(eb)
                    }
                }));
                dS.referrerPolicy = "origin";
                dS.src = "https://preview.colorlib.com/cdn-cgi/zaraz/s.js?z=" + btoa(encodeURIComponent(JSON.stringify(dK[dM])));
                dR.parentNode.insertBefore(dS, dR)
            };
            ["complete", "interactive"].includes(dL.readyState) ? zaraz.init() : dK.addEventListener("DOMContentLoaded", zaraz.init)
        }(w, d, "zarazData", "script");
    })(window, document);</script>
</head>
<body>

<div id="preloader">
    <div class="loader"></div>
</div>

{% include 'header.html' %}

{% for message in messages %}
    {% if 'success' in message.tags %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% elif 'info' in message.tags %}
        <div class="alert alert-info" role="alert">
            {{ message }}
        </div>
    {% elif 'warning' in message.tags %}
        <div class="alert alert-warning" role="alert">
            {{ message }}
        </div>
    {% elif 'error' in message.tags %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
    {% endif %}
{% endfor %}


{% block content %}


{% endblock %}

<section class="roberto-cta-area">
    <div class="container">
        <div class="cta-content bg-img bg-overlay jarallax"
             style="background-image: url({% static 'img/bg-img/1.jpg' %});">
            <div class="row align-items-center">
                <div class="col-12 col-md-7">
                    <div class="cta-text mb-50">
                        <h2>Contact us now!</h2>
                        <h6>Contact (+12) 345-678-9999 to book directly or for advice</h6>
                    </div>
                </div>
                <div class="col-12 col-md-5 text-right">
                    <a href="{% url 'contact:contact' %}" class="btn roberto-btn mb-50">Contact Now</a>
                </div>
            </div>
        </div>
    </div>
</section>


<div class="partner-area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="partner-logo-content d-flex align-items-center justify-content-between wow fadeInUp"
                     data-wow-delay="300ms">

                    <a href="#" class="partner-logo"><img src="{% static 'img/core-img/p1.png' %}" alt=""></a>

                    <a href="#" class="partner-logo"><img src="{% static 'img/core-img/p2.png' %}" alt=""></a>

                    <a href="#" class="partner-logo"><img src="{% static 'img/core-img/p3.png' %}" alt=""></a>

                    <a href="#" class="partner-logo"><img src="{% static 'img/core-img/p4.png' %}" alt=""></a>

                    <a href="#" class="partner-logo"><img src="{% static 'img/core-img/p5.png' %}" alt=""></a>
                </div>
            </div>
        </div>
    </div>
</div>


{% include 'footer.html' %}


<script src="{% static 'js/jquery.min.js' %}"></script>

<script src="{% static 'js/popper.min.js' %}"></script>

<script src="{% static 'js/bootstrap.min.js' %}"></script>

<script src="{% static 'js/roberto.bundle.js' %}"></script>

<script src="{% static 'js/default-assets/active.js' %}"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-23581568-13');
</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v52afc6f149f6479b8c77fa569edb01181681764108816"
        integrity="sha512-jGCTpDpBAYDGNYR5ztKt4BQPGef1P0giN6ZGVUi835kFF88FOmmn8jBQWNgrNd8g/Yu421NdgWhwQoaOPFflDw=="
        data-cf-beacon='{"rayId":"7db5547a694904ff","version":"2023.4.0","b":1,"token":"cd0b4b3a733644fc843ef0b185f98241","si":100}'
        crossorigin="anonymous"></script>
</body>

</html>

templates/footer.html
{% load static %}
<footer class="footer-area section-padding-80-0">

    <div class="main-footer-area">
        <div class="container">
            <div class="row align-items-baseline justify-content-between">

                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="single-footer-widget mb-80">

                        <a href="#" class="footer-logo"><img src="{% static 'img/core-img/logo2.png' %}" alt=""></a>
                        <h4>+12 345-678-9999</h4>
                        <span><a href="https://preview.colorlib.com/cdn-cgi/l/email-protection" class="__cf_email__"
                                 data-cfemail="baf3d4dcd594d9d5d6d5c8d6d3d8faddd7dbd3d694d9d5d7">[email&#160;protected]</a></span>
                        <span>856 Cordia Extension Apt. 356, Lake Deangeloburgh, South Africa</span>
                    </div>
                </div>

                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="single-footer-widget mb-80">

                        <h5 class="widget-title">Our Blog</h5>

                        <div class="latest-blog-area">
                            <a href="#" class="post-title">Freelance Design Tricks How</a>
                            <span class="post-date"><i class="fa fa-clock-o" aria-hidden="true"></i> Jan 02, 2019</span>
                        </div>

                        <div class="latest-blog-area">
                            <a href="#" class="post-title">Free Advertising For Your Online</a>
                            <span class="post-date"><i class="fa fa-clock-o" aria-hidden="true"></i> Jan 02, 2019</span>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-sm-4 col-lg-2">
                    <div class="single-footer-widget mb-80">

                        <h5 class="widget-title">Links</h5>

                        <ul class="footer-nav">
                            <li><a href="{% url 'home:about' %}"><i class="fa fa-caret-right" aria-hidden="true"></i> About Us</a></li>
                            <li><a href="{% url 'booking:room' %}"><i class="fa fa-caret-right" aria-hidden="true"></i> Our Rooms</a></li>
                            <li><a href="{% url 'contact:contact' %}"><i class="fa fa-caret-right" aria-hidden="true"></i> Contact</a></li>
                            <li><a href="{% url 'blog:blog' %}"><i class="fa fa-caret-right" aria-hidden="true"></i> Blogs</a></li>
                            <li><a href="{% url 'home:index' %}"><i class="fa fa-caret-right" aria-hidden="true"></i> Home</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-12 col-sm-8 col-lg-4">
                    <div class="single-footer-widget mb-80">

                        <h5 class="widget-title">Subscribe Newsletter</h5>
                        <span>Subscribe our newsletter gor get notification about new updates.</span>

                        <form action="https://preview.colorlib.com/theme/roberto/index.html" class="nl-form">
                            <input type="email" class="form-control" placeholder="Enter your email...">
                            <button type="submit"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="copywrite-content">
            <div class="row align-items-center">
                <div class="col-12 col-md-8">

                    <div class="copywrite-text">
                        <p>
                            Copyright &copy;<script data-cfasync="false"
                                                    src="https://preview.colorlib.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
                            <script>document.write(new Date().getFullYear());</script>
                            All rights reserved | This template is made with <i class="fa fa-heart-o"
                                                                                aria-hidden="true"></i> by <a
                                href="https://colorlib.com/" target="_blank">Colorlib</a>
                        </p>
                    </div>
                </div>
                <div class="col-12 col-md-4">

                    <div class="social-info">
                        <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                        <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                        <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                        <a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/header.html
{% load static %}
<header class="header-area">

    <div class="search-form d-flex align-items-center">
        <div class="container">
            <form action="https://preview.colorlib.com/theme/roberto/index.html" method="get">
                <input type="search" name="search-form-input" id="searchFormInput" placeholder="Type your keyword ...">
                <button type="submit"><i class="icon_search"></i></button>
            </form>
        </div>
    </div>

    <div class="top-header-area">
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <div class="top-header-content">
                        <a href="#"><i class="icon_phone"></i> <span>(123) 456-789-1230</span></a>
                        <a href="#"><i class="icon_mail"></i> <span><span class="__cf_email__"
                                                                          data-cfemail="f59c9b939adb969a999a87999c97b59298949c99db969a98">[email&#160;protected]</span></span></a>
                    </div>
                </div>
                <div class="col-6">
                    <div class="top-header-content">

                        <div class="top-social-area ml-auto">
                            <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-tripadvisor" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="main-header-area">
        <div class="classy-nav-container breakpoint-off">
            <div class="container">

                <nav class="classy-navbar justify-content-between" id="robertoNav">

                    <a class="nav-brand" href="{% url 'home:index' %}"><img src="{% static 'img/core-img/logo.png' %}"
                                                                            alt=""></a>

                    <div class="classy-navbar-toggler">
                        <span class="navbarToggler"><span></span><span></span><span></span></span>
                    </div>

                    <div class="classy-menu">

                        <div class="classycloseIcon">
                            <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                        </div>

                        <div class="classynav">
                            <ul id="nav">

                                <li class="active"><a href="{% url 'home:index' %}">Home</a></li>
                                <li><a href="{% url 'booking:room' %}">Rooms</a></li>
                                <li><a href="{% url 'home:about' %}">About Us</a></li>
                                <li><a href="#">Pages</a>
                                    <ul class="dropdown">
                                        <li><a href="{% url 'home:index' %}">- Home</a></li>
                                        <li><a href="{% url 'booking:room' %}">- Rooms</a></li>
                                        <li><a href="{% url 'home:about' %}">- About Us</a></li>
                                        <li><a href="{% url 'blog:blog' %}">- Blog</a></li>
                                        <li><a href="{% url 'contact:contact' %}">- Contact</a></li>
                                        {#                                        <li><a href="#">- Dropdown</a>#}
                                        {#                                            <ul class="dropdown">#}
                                        {#                                                <li><a href="#">- Dropdown Item</a></li>#}
                                        {#                                                <li><a href="#">- Dropdown Item</a></li>#}
                                        {#                                                <li><a href="#">- Dropdown Item</a></li>#}
                                        {#                                                <li><a href="#">- Dropdown Item</a></li>#}
                                        {#                                            </ul>#}
                                        {#                                        </li>#}
                                    </ul>
                                </li>
                                <li><a href="{% url 'contact:contact' %}">Contact</a></li>
                            </ul>

                            <div class="search-btn ml-4">
                                <i class="fa fa-search" aria-hidden="true"></i>
                            </div>


                        </div>

                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>

templates/sidebar.html
{% load static %}
{% load resent_blogs %}
{% resent_blog as r_b %}
{% get_tags as tags %}
<div class="col-12 col-sm-8 col-md-6 col-lg-4">
    <div class="roberto-sidebar-area pl-md-4">

        <div class="single-widget-area mb-100">
            <div class="newsletter-form">
                <h5>Newsletter</h5>
                <p>Subscribe our newsletter gor get notification new updates.</p>
                <form action="#" method="post">
                    <input type="email" name="nl-email" id="nlEmail" class="form-control"
                           placeholder="Enter your email...">
                    <button type="submit" class="btn roberto-btn w-100">Subscribe</button>
                </form>
            </div>
        </div>

        <div class="single-widget-area mb-100">
            <h4 class="widget-title mb-30">Recent News</h4>

            {% for new in r_b.all %}
                <div class="single-recent-post d-flex">
                    {% if new.image %}
                        <div class="post-thumb">
                            <a href=""><img src="{{ new.image.url }}"
                                            alt=""></a>
                        </div>
                    {% endif %}

                    <div class="post-content">

                        <div class="post-meta">
                            <a href="" class="post-author">{{ new.created_date|date:"F d, Y" }}</a>
                            <a href="{{ new.url_detail_blog }}" class="post-tutorial">Event</a>
                        </div>
                        <a href="{{ new.url_detail_blog }}" class="post-title">{{ new.title }}</a>
                    </div>
                </div>

            {% endfor %}


        </div>

        <div class="single-widget-area mb-100 clearfix">
            <h4 class="widget-title mb-30">Tags</h4>

            <ul class="popular-tags">
                {% for tag in tags %}
                    <li><a href="{% url 'blog:blog' %}?tag={{ tag.title }}">{{ tag.title }}</a></li>
                {% endfor %}
            </ul>
        </div>

        <div class="single-widget-area mb-100 clearfix">
            <h4 class="widget-title mb-30">Instagram</h4>

            <ul class="instagram-feeds">
                <li><a href="#"><img src="{% static 'img/bg-img/33.jpg' %}" alt=""></a></li>
                <li><a href="#"><img src="{% static 'img/bg-img/34.jpg' %}" alt=""></a></li>
                <li><a href="#"><img src="{% static 'img/bg-img/35.jpg' %}" alt=""></a></li>
                <li><a href="#"><img src="{% static 'img/bg-img/36.jpg' %}" alt=""></a></li>
                <li><a href="#"><img src="{% static 'img/bg-img/37.jpg' %}" alt=""></a></li>
                <li><a href="#"><img src="{% static 'img/bg-img/38.jpg' %}" alt=""></a></li>
            </ul>
        </div>
    </div>
</div>